<a href="https://colab.research.google.com/github/shayanAbbasi1995/UAB-Thesis/blob/main/Matching_firm_ticker3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Run this if running in Google Collab
# Mount google drive if running from Google Collab
from google.colab import drive
drive.mount('/content/drive')

# Set current directory if running from Google Collab

import os
os.chdir('/content/drive/My Drive/Colab Notebooks/Master Project')# here use your path to current notebook

Mounted at /content/drive

In [ ]:
import pandas as pd
from nltk.tokenize import word_tokenize
import nltk
nltk.download('punkt')
import numpy as np

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.

In [ ]:
litigations = pd.read_csv('Competition related violations.csv')
ticker_list = pd.read_excel('Ticker_List.xlsx')
firm_code = pd.read_stata('Firm-code-info.dta')

In [ ]:
litigations

,Company,Parent Company,Penalty Amount,Subtraction From Penalty,Penalty Amount Adjusted For Eliminating Multiple Counting,Penalty Year,Penalty Date,Offense Group,Primary Offense,Secondary Offense,...,NAICS Code,NAICS Translation,HQ Country of Parent,HQ State of Parent,Ownership Structure,Parent Company Stock Ticker,Major Industry of Parent,Specific Industry of Parent,Info Source,Notes
0,1-800-East-West Mortgage Company,NaN,"$150,000",$0,"$150,000",2006,20060906,competition-related offenses,kickbacks and bribery,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://archives.hud.gov/news/2006/pr06-106.cfm,NaN
1,"3-State Stockyards, Inc.",NaN,"$6,750",$0,"$6,750",2002,20020424,competition-related offenses,agribusiness violation,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.gipsa.usda.gov/Newrelease/2002NR.pdf,NaN
2,"3-State Stockyards, Inc.",NaN,"$43,000",$0,"$43,000",2013,20130815,competition-related offenses,agribusiness violation,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.gipsa.usda.gov/Newrelease/2013NR.pdf,NaN
3,3DSP Corporation,NaN,"$36,000",$0,"$36,000",2007,20071212,competition-related offenses,export control violation,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://efoia.bis.doc.gov/index.php/component/...,NaN
4,3-G Mermet Corporation,NaN,"$17,500",$0,"$17,500",2004,20041018,competition-related offenses,export control violation,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FOIA242,Source document obtained through a Freedom of ...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2829,NatWest Markets Plc,NatWest Group PLC,"$35,000,000",$0,"$35,000,000",2021,20211221,competition-related offenses,fraud,investor protection violation,...,NaN,NaN,United Kingdom,NaN,government-owned,LSE: NWG,financial services,banking & securities,https://www.justice.gov/opa/pr/natwest-markets...,NaN
2830,"Torrey Pines Logic, Inc.",NaN,"$840,000",$0,"$840,000",2022,20220121,competition-related offenses,export control violation,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.pmddtc.state.gov/sys_attachment.do...,NaN
2831,Women's Health USA et al.,NaN,"$1,252,401",$0,"$1,252,401",2021,20210913,competition-related offenses,price-fixing or anti-competitive practices,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://portal.ct.gov/AG/Press-Releases/2021-P...,NaN
2832,Reproductive Medicine Associates of CT,NaN,"$348,856",$0,"$348,856",2021,20210913,competition-related offenses,price-fixing or anti-competitive practices,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://portal.ct.gov/AG/Press-Releases/2021-P...,NaN
2833,"Atlantic Veal & Lamb, LLC",NaN,"$7,500",$0,"$7,500",2022,20220225,competition-related offenses,agribusiness violation,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.ams.usda.gov/press-release/usda-se...,NaN

In [ ]:
ticker_list

,stock_ticker,parent_name,pen_total,num_recs,name_all,rank,ownership,russell3000,hq_country,hq_state,industry,major_industry,viol_parent_url,sub_parent_url,csw_link
0,FLWS,1-800-Flowers.com,38181,4,"CHERYL & CO; FANNIE MAY CONFECTIONS BRANDS, IN...",2935,publicly traded,yes,USA,New York,retail-internet flowers,retailing,https://violationtracker.goodjobsfirst.org/par...,https://subsidytracker.goodjobsfirst.org/paren...,NaN
1,DDD,3D Systems,176637,4,3D SYS,2574,publicly traded,yes,USA,South Carolina,3-D printers,miscellaneous manufacturing,https://violationtracker.goodjobsfirst.org/par...,https://subsidytracker.goodjobsfirst.org/paren...,NaN
2,MMM,3M Company,883252467,84,3M; 3M ATTENTI; 3M AUSTIN CENTER; 3M COLLEGE S...,90,publicly traded,yes,USA,Minnesota,diversified,miscellaneous manufacturing,https://violationtracker.goodjobsfirst.org/par...,https://subsidytracker.goodjobsfirst.org/paren...,NaN
3,AHC,A.H. Belo,2500000,1,BELO,1618,publicly traded,NaN,USA,Texas,media,media,https://violationtracker.goodjobsfirst.org/par...,https://subsidytracker.goodjobsfirst.org/paren...,NaN
4,CTAM,A.M. Castle & Co.,951472,11,AM CASTLE; AM CASTLE AND,1978,publicly traded,NaN,USA,Illinois,metals service centers,metals,https://violationtracker.goodjobsfirst.org/par...,https://subsidytracker.goodjobsfirst.org/paren...,https://data.covidstimuluswatch.org/parent/am-...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1428,ZG,Zillow Group,8462888,2,"Zillow, Inc.",1158,publicly traded,yes,USA,Washington,real estate information services,miscellaneous services,https://violationtracker.goodjobsfirst.org/par...,https://subsidytracker.goodjobsfirst.org/paren...,NaN
1429,ZBH,Zimmer Biomet,246074182,13,BIOMET; BIOMET FAIR LAWN LP; BIOMET ORTHOPEDIC...,237,publicly traded,yes,USA,Indiana,medical devices,medical equipment and supplies,https://violationtracker.goodjobsfirst.org/par...,https://subsidytracker.goodjobsfirst.org/paren...,NaN
1430,ZION,Zions Bancorporation,11615347,3,ZB NA FKA ZIONS FIRST NATIONAL BANK; ZIONS,1035,publicly traded,yes,USA,Utah,banking,financial services,https://violationtracker.goodjobsfirst.org/par...,https://subsidytracker.goodjobsfirst.org/paren...,NaN
1431,ZTS,Zoetis,127433,7,ALPHARMA2; FORT DODGE; ZOETIS,2667,publicly traded,yes,USA,New Jersey,animal health products,pharmaceuticals,https://violationtracker.goodjobsfirst.org/par...,https://subsidytracker.goodjobsfirst.org/paren...,NaN
1432,ZVO,Zovio Inc.,31500000,1,BRIDGEPOINT EDUCATION,694,publicly traded,yes,USA,Arizona,educational services,miscellaneous services,https://violationtracker.goodjobsfirst.org/par...,https://subsidytracker.goodjobsfirst.org/parent/,NaN

In [ ]:
firm_code

,gvkey,datadate,fyear,indfmt,consol,popsrc,datafmt,tic,cusip,conm,curcd,fyr,exchg,cik,costat,fic
0,001000,1961-12-31,1961.0,INDL,C,D,STD,AE.2,000032102,A & E PLASTIK PAK INC,USD,12.0,12.0,,I,USA
1,001000,1962-12-31,1962.0,INDL,C,D,STD,AE.2,000032102,A & E PLASTIK PAK INC,USD,12.0,12.0,,I,USA
2,001000,1963-12-31,1963.0,INDL,C,D,STD,AE.2,000032102,A & E PLASTIK PAK INC,USD,12.0,12.0,,I,USA
3,001000,1964-12-31,1964.0,INDL,C,D,STD,AE.2,000032102,A & E PLASTIK PAK INC,USD,12.0,12.0,,I,USA
4,001000,1965-12-31,1965.0,INDL,C,D,STD,AE.2,000032102,A & E PLASTIK PAK INC,USD,12.0,12.0,,I,USA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
590008,351491,2019-12-31,2019.0,INDL,C,D,STD,IVCGF,N47017103,IVECO GROUP N V,USD,12.0,19.0,,A,NLD
590009,351491,2020-12-31,2020.0,INDL,C,D,STD,IVCGF,N47017103,IVECO GROUP N V,USD,12.0,19.0,,A,NLD
590010,351590,2019-12-31,2019.0,INDL,C,D,STD,DTRUY,23384L101,DAIMLER TRUCK HOLDING AG,USD,12.0,19.0,0001890567,A,DEU
590011,351590,2020-12-31,2020.0,INDL,C,D,STD,DTRUY,23384L101,DAIMLER TRUCK HOLDING AG,USD,12.0,19.0,0001890567,A,DEU
590012,351590,2021-12-31,2021.0,INDL,C,D,STD,DTRUY,23384L101,DAIMLER TRUCK HOLDING AG,USD,12.0,19.0,0001890567,A,DEU

In [ ]:
litigations['Company'] = litigations['Company'].str.lower()
firm_code['conm'] = firm_code['conm'].str.lower()
litigations['Parent Company'] = litigations['Parent Company'].str.lower()

In [ ]:
final_df = litigations.merge(firm_code, right_on='conm', left_on='Company', how='left')

In [ ]:
final_df.tic.value_counts()

BCS       328
DB        290
AIG       180
JNJ       144
MEC2      142
BCS.PD    108
3614B     100
LYG        88
ASO.1      86
NVO        86
BNS        80
RY         80
MS         74
NE         74
UNM        73
ABT        72
AVP        69
GSK        62
HP         62
ITW        60
BAYRY      58
SIEGY      56
BAESY      54
NVS        52
SAP        52
AMD        50
IFNNY      48
FTI        46
MBT        44
TLSNY      42
EP.1       39
WPP        36
SNN        32
AZN        30
DEO        27
ABB        25
ENDP       23
SNY        22
ALIZY      22
ITT.1      21
BUD        15
MNKKQ      11
LYB1       10
9773B       9
MET1        8
CMRK        7
HOE         5
Name: tic, dtype: int64

In [ ]:
len(litigations.Company.unique())

2590

In [ ]:
len(final_df.conm.unique())

48

In [ ]:
def is_similar(item, code):
  counter = 0
  item_list = word_tokenize(item)
  try:
    item_list.remove('.')
  except:
    pass
  try:
    item_list.remove(',')
  except:
    pass
  code_list = word_tokenize(code)
  try:
    code_list.remove('.')
  except:
    pass
  try:
    code_list.remove(',')
  except:
    pass
  for word in item_list:
    if word in code_list:
      counter += 1
  if counter/len(code_list) >= 0.6:
    return True
  else:
    return False

In [ ]:
conm_code = firm_code.conm.unique()
comp_code = litigations.Company.unique()
comp2_code = litigations['Parent Company'].unique()[1:]

In [ ]:
litigations['conm'] = np.nan
litigations['conm2'] = np.nan
for item in comp_code[200:300]:
  print(f'item = {item}')
  conm_list = []
  for jtem in conm_code:
    if is_similar(item, jtem):
      conm_list.append(jtem)
  litigations.conm[litigations.Company == item] = str(conm_list)
for ktem in comp2_code[200:300]:
  conm2_list = []
  for jtem in conm_code:
    if is_similar(ktem, jtem):
      conm2_list.append(jtem)
  litigations.conm2[litigations['Parent Company'] == ktem] = str(conm2_list)
litigations.to_csv('litigations_w_conm1_conm2_200_300.csv')

item = becton, dickinson and company

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':

item = beefco
item = bef corporation
item = beken livestock, inc.
item = bell lumber and pole company
item = bellsouth corporation
item = benison transport, inc. and shine international transportation (shenzhen) ltd.
item = bennett environmental inc.
item = berger cattle company
item = berkeley nucleonics corporation
item = berkshire power company llc and power plant management services llc
item = bernuth lines ltd
item = berry & son rababeh islamic slaughter house inc.
item = bhp billiton
item = bib industrie
item = bilfinger se
item = bio check inc.
item = bio-rad laboratories inc.
item = biomet inc.
item = bioscrip inc.
item = biospherical instruments, inc.
item = birdsboro kosher farm corporation
item = bizjet international sales and support inc.
item = bj services co.
item = bj services company usa, lp
item = bk medical aps
item = black hills power, inc.
item = black, sivalls & bryson (uk) ltd
item = blue cargo group llc, dba blu logistics
item = blue cross & blue shield of rhode island
item = blue horse company, llc
item = bnp paribas s.a.
item = bny mellon
item = the boeing company
item = boeing satellite systems
item = boston scientific corporation
item = bp products north america inc.
item = bp energy company
item = bp livestock, llc
item = braskem s.a
item = braskem s.a.
item = brian min d.b.a. b & a express
item = bridgestone corp.
item = brighton equipment corporation
item = bristol-myers squibb
item = bristol-myers squibb medical imaging, inc.
item = british airways plc
item = british association of removers ltd
item = bro pack, inc.
item = brookfield power us assets management, llc
item = bropack enterprises, llc
item = bruker corporation
item = bruker axs, inc.
item = bs&b process systems inc.
item = buehler limited
item = buehler united kingdom
item = bullard gmbh
item = bumble bee foods llc
item = byram healthcare centers inc.
item = c.a. litzler co., inc.
item = cabela's inc.
item = caddell construction company inc.
item = caliber inc.
item = california financial services, inc., internet telecommunications albany system smr, internet telecommunications reno system smr and internet telecommu
item = california fresh meats
item = california independent system operator
item = california independent system operator corporation
item = calpine energy services, l.p.
item = cambridge valley livestock market, inc.
item = canberra albuquerque
item = capintec, inc.
item = carbone of america industries corp.
item = carga tica international, inc.
item = cargill meat solutions corporation
item = cargill meat solutions, inc.
item = cargo alliance inc.
item = cargo cargo logistics inc.
item = cargo-partner network, b.v
item = cargoland air and ocean cargo, inc.
item = cargolux airlines international s.a.
item = cargonauts, inc.
item = caribbean freight systems inc.
item = caribbean general maritime, ltd.
item = carl zeiss optical inc.
item = carlo shipping international, inc.
item = carrier access corporation
item = cartwright international van lines inc.
item = cathay pacific airways limited
item = central beef ind., llc
item = central beef industries, llc
item = central valley property group, inc., d/b/a mdm meat co.
item = cerac inc.
item = certified slings inc.
item = c.h. cattle company, llc
item = c.h. robinson project logistics, inc.
item = ch2m hill hanford group inc.
item = chebanse grain, inc.
item = cheil jedang corporation
item = chemical partners europe s.a.
item = chester d. coleman & cookie coleman cattle company, inc.

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  from ipykernel import kernelapp as app

In [ ]:
litigations

,Company,Parent Company,Penalty Amount,Subtraction From Penalty,Penalty Amount Adjusted For Eliminating Multiple Counting,Penalty Year,Penalty Date,Offense Group,Primary Offense,Secondary Offense,...,HQ Country of Parent,HQ State of Parent,Ownership Structure,Parent Company Stock Ticker,Major Industry of Parent,Specific Industry of Parent,Info Source,Notes,conm,conm2
0,1-800-east-west mortgage company,NaN,"$150,000",$0,"$150,000",2006,20060906,competition-related offenses,kickbacks and bribery,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,https://archives.hud.gov/news/2006/pr06-106.cfm,NaN,NaN,NaN
1,"3-state stockyards, inc.",NaN,"$6,750",$0,"$6,750",2002,20020424,competition-related offenses,agribusiness violation,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,https://www.gipsa.usda.gov/Newrelease/2002NR.pdf,NaN,NaN,NaN
2,"3-state stockyards, inc.",NaN,"$43,000",$0,"$43,000",2013,20130815,competition-related offenses,agribusiness violation,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,https://www.gipsa.usda.gov/Newrelease/2013NR.pdf,NaN,NaN,NaN
3,3dsp corporation,NaN,"$36,000",$0,"$36,000",2007,20071212,competition-related offenses,export control violation,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,https://efoia.bis.doc.gov/index.php/component/...,NaN,NaN,NaN
4,3-g mermet corporation,NaN,"$17,500",$0,"$17,500",2004,20041018,competition-related offenses,export control violation,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,FOIA242,Source document obtained through a Freedom of ...,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2829,natwest markets plc,natwest group plc,"$35,000,000",$0,"$35,000,000",2021,20211221,competition-related offenses,fraud,investor protection violation,...,United Kingdom,NaN,government-owned,LSE: NWG,financial services,banking & securities,https://www.justice.gov/opa/pr/natwest-markets...,NaN,NaN,NaN
2830,"torrey pines logic, inc.",NaN,"$840,000",$0,"$840,000",2022,20220121,competition-related offenses,export control violation,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,https://www.pmddtc.state.gov/sys_attachment.do...,NaN,NaN,NaN
2831,women's health usa et al.,NaN,"$1,252,401",$0,"$1,252,401",2021,20210913,competition-related offenses,price-fixing or anti-competitive practices,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,https://portal.ct.gov/AG/Press-Releases/2021-P...,NaN,NaN,NaN
2832,reproductive medicine associates of ct,NaN,"$348,856",$0,"$348,856",2021,20210913,competition-related offenses,price-fixing or anti-competitive practices,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,https://portal.ct.gov/AG/Press-Releases/2021-P...,NaN,NaN,NaN
2833,"atlantic veal & lamb, llc",NaN,"$7,500",$0,"$7,500",2022,20220225,competition-related offenses,agribusiness violation,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,https://www.ams.usda.gov/press-release/usda-se...,NaN,NaN,NaN